
server:
  servlet:
    context-path: /api

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
      show-sql: false
  datasource:
    url: jdbc:h2:file:./pricelistscrubber
    username: sa
    password: password


pchub-data-url: https://sheets.googleapis.com//v4/spreadsheets/10bTlhxgBCCsFCD3wvGMvHzDqKOOFqR-iFpiJFtTHirA/values/PLs!A8:U?key=AIzaSyCIdLw59N8o9vLSdb20BVwHzRAcyYoyewg
